# Generated by Django 3.2.8 on 2022-08-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateways', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgateway',
            name='title',
            field=models.CharField(choices=[('2checkout', '2Checkout'), ('paystack', 'Paystack'), ('stripe', 'Stripe')], max_length=10),
        ),
    ]
