# Generated by Django 3.2.8 on 2021-10-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='', max_length=500)),
                ('desc', models.CharField(default='', max_length=500)),
                ('plan_type', models.CharField(blank=True, default='', max_length=20)),
                ('trialDurationInDays', models.IntegerField(default=7)),
            ],
        ),
    ]
