# Generated by Django 3.2.8 on 2021-10-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='ui_json',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
