# Generated by Django 3.2.8 on 2022-04-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_plans', '0003_addon'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='is_addon',
            field=models.BooleanField(default=False),
        ),
    ]
