# Generated by Django 3.2.8 on 2022-04-13 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_plans', '0005_pricingplan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
