# Generated by Django 3.2.8 on 2022-04-14 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_plans', '0006_pricingplan_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='access_type',
            field=models.CharField(choices=[('PLAN', 'Plan'), ('CONSULTANT', 'Consultant'), ('FORMS2EMAIL', 'Forms2Email'), ('NO_ACCESS', 'No Access')], default='NO_ACCESS', max_length=20),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='plan_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('enterprise', 'Enterprise')], default='individual', max_length=20),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='status',
            field=models.CharField(choices=[('PUBLISH', 'Publish'), ('HIDE', 'Hide')], default='PUBLISH', max_length=10),
        ),
    ]
