# Generated by Django 3.2.8 on 2022-04-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_plans', '0007_auto_20220415_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='plan_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('ENTERPRISE', 'Enterprise')], default='individual', max_length=20),
        ),
    ]
