# Generated by Django 3.2.8 on 2022-04-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_plans', '0008_auto_20220415_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingplan',
            name='link',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
