# Generated by Django 3.2.8 on 2022-08-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_plans', '0010_pricingplan_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingplan',
            name='ui_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
