# Generated by Django 3.2.15 on 2022-08-15 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('email_templates', '0002_auto_20220811_0303'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('to', models.EmailField(max_length=254)),
                ('reply_to', models.EmailField(max_length=254)),
                ('send_user_email', models.BooleanField(default=False)),
                ('admin_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_template', to='email_templates.useremailtemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('user_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_template', to='email_templates.useremailtemplate')),
            ],
        ),
    ]
