# Generated by Django 3.2.8 on 2022-04-13 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='plan_type',
            field=models.CharField(default='PLAN', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.IntegerField(),
        ),
    ]
