# Generated by Django 3.2.8 on 2022-04-14 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20220413_0725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='plan_type',
            new_name='access_type',
        ),
    ]
