# Generated by Django 3.2.8 on 2022-05-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_rename_plan_type_subscription_access_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment_gateway',
            field=models.CharField(default='stripe', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_gateway_auth_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
