# Generated by Django 3.2.8 on 2022-08-10 23:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_auto_20220524_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='statusDateTime',
        ),
        migrations.AddField(
            model_name='subscription',
            name='status_update_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 4, 39, 10, 158864)),
        ),
    ]
