# Generated by Django 3.2.8 on 2022-08-10 23:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_auto_20220811_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status_update_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 10, 23, 48, 48, 50911, tzinfo=utc)),
        ),
    ]
