# Generated by Django 3.2.8 on 2022-08-10 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_alter_subscription_status_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status_update_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
