# Generated by Django 3.2.15 on 2022-08-21 22:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('email_templates', '0002_auto_20220811_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremailtemplate',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useremailtemplate',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='useremailtemplate',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
