# Generated by Django 3.2.8 on 2022-08-04 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment_gateways', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('pg_payment_method_id', models.CharField(max_length=50)),
                ('verified', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('payment_gateway', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment_gateways.paymentgateway')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
