# Generated by Django 3.2.15 on 2022-09-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_identities', '0002_emailidentity_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailidentity',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
