# Generated by Django 3.2.15 on 2022-09-15 06:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('email_identities', '0005_alter_emailidentity_email'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emailidentity',
            unique_together={('user', 'email')},
        ),
    ]
