# Generated by Django 3.2.15 on 2022-11-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_identities', '0006_alter_emailidentity_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailidentity',
            name='first_name',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailidentity',
            name='last_name',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
