# Generated by Django 3.2.8 on 2021-11-12 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '0002_campaignexecutionlog_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('minute', models.CharField(default='*', max_length=1)),
                ('hour', models.CharField(default='*', max_length=1)),
                ('day_of_month', models.CharField(default='*', max_length=1)),
                ('month', models.CharField(default='*', max_length=1)),
                ('day_of_week', models.CharField(default='*', max_length=1)),
                ('max_executions', models.IntegerField(default=0)),
                ('current_executions', models.IntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campaigns.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
