# Generated by Django 3.2.8 on 2022-04-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_campaigntag'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='email_preview_text',
            field=models.CharField(default='', max_length=150),
        ),
    ]
