# Generated by Django 3.2.15 on 2022-12-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('audience', '0002_auto_20220104_0230'),
        ('campaigns', '0006_campaign_email_preview_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='to_tags',
            field=models.ManyToManyField(blank=True, null=True, to='tags.Tag'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='to_audience',
            field=models.ManyToManyField(blank=True, null=True, to='audience.Audience'),
        ),
    ]
