# Generated by Django 3.2.15 on 2023-11-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('audience', '0002_auto_20220104_0230'),
        ('campaigns', '0007_auto_20221215_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='to_audience',
            field=models.ManyToManyField(blank=True, to='audience.Audience'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='to_tags',
            field=models.ManyToManyField(blank=True, to='tags.Tag'),
        ),
    ]
