# Generated by Django 3.2.8 on 2022-05-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('userId', models.IntegerField()),
                ('payment_gateway', models.CharField(max_length=15)),
                ('authorization_code', models.CharField(blank=True, max_length=50, null=True)),
                ('bin', models.CharField(blank=True, max_length=10, null=True)),
                ('channel', models.CharField(blank=True, max_length=20, null=True)),
                ('last4', models.CharField(blank=True, max_length=4, null=True)),
                ('exp_month', models.CharField(blank=True, max_length=2, null=True)),
                ('exp_year', models.CharField(blank=True, max_length=4, null=True)),
                ('card_type', models.CharField(blank=True, max_length=50, null=True)),
                ('bank', models.CharField(blank=True, max_length=50, null=True)),
                ('country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('reusable', models.BooleanField()),
                ('signature', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='authorization_url',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='paymentevent',
            name='post_data',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentGateway',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
