# Generated by Django 3.2.8 on 2022-08-11 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_rename_userid_paymentevent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentevent',
            name='type',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
