# Generated by Django 3.2.15 on 2022-08-24 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('payments', '0005_alter_payment_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='userId',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='orders.order'),
            preserve_default=False,
        ),
    ]
