# Generated by Django 3.2.15 on 2022-08-24 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20220825_0104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='user',
            new_name='userId',
        ),
    ]
