# Generated by Django 3.2.8 on 2021-10-25 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pricing_plans', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_type', models.CharField(default='', max_length=500)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('country', models.CharField(default='US', max_length=2)),
                ('pricing_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing_plans.pricingplan')),
            ],
        ),
    ]
