# Generated by Django 3.2.8 on 2022-04-15 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charge_options', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargeoption',
            name='upsell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='charge_options.chargeoption'),
        ),
        migrations.AddField(
            model_name='chargeoption',
            name='upsell_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='chargeoption',
            name='upsell_message',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
